title = "Translate peptides from sequence"

# number of processors
nproc = 6

# translate peptides from dna sequence
translate = true
peptide-length = 12
translated-strand = true
# dna or amino acid sequence
peptide-fasta = "./sample1.fastq"
# primers
forward-primer = "CCTCTCTATGGGCAGTCGGTGATCCTTTCTATTCTCACTCT"
reverse-primer = "CCGAACCTCCACC"

# map hits in protein sequences
mapping = false
# protein sequences
protein-fasta = "./Rrproteoma.fasta"
# number of random sequences to estimate error
nrandom = 3
# score function exponent
exp-score = 2.0
quadrant-window = 7
