title = "TOML config example"

# numero de processadores
nproc = 6
peptide-length = 12
protein-fasta = "./Rrproteoma.fasta"
peptide-fasta = ["./sample1.fastq"]
forward-primer = "CCTCTCTATGGGCAGTCGGTGATCCTTTCTATTCTCACTCT"
reverse-primer = "CCGAACCTCCACC"

# numero de bibliotecas randômicas para estimar o erro
nrandom = 3
# expoente da função de score
exp-score = 2.0
# janela da análise quadrant
quadrant-window = 7
