title = "TOML config example"

# numero de processadores
nproc = 6
# protein sequence
protein-fasta = "./Rrproteoma.fasta"
# translate peptides from dna sequence
translate = true
peptide-length = 12
# dna or amino acid sequence
peptide-fasta = "./sample1.fastq"
# primers
forward-primer = "CCTCTCTATGGGCAGTCGGTGATCCTTTCTATTCTCACTCT"
reverse-primer = "CCGAACCTCCACC"

# numero de bibliotecas randômicas para estimar o erro
nrandom = 3
# expoente da função de score
exp-score = 2.0
# janela da análise quadrant
quadrant-window = 7
